### ISSUE TITLE
Search not returning results

### ISSUE THREAD

**Issue by jodette** [CommunityHealthAcademy/django-covid#50]
![image](https://user-images.githubusercontent.com/55252848/82709502-bcf86900-9c4e-11ea-8be3-f2caf22a46ab.png)

Not sure if that image is going to work, but when I search 'spitting' from the homepage (knowing there's a resource titled spitting) I see 1 Result on the left hand side and but no resources returned (just reads None on the right side)

**Comment by alexlittle** [comment]
Seems that it is picking up the right number of expected results - see:  https://covid-19library.org/search/?q=infographic - which returns the expected no results (5) - only that it's not picking up the info about the resource.

It works from the advanced search page though, see:  https://covid-19library.org/search/advanced/results/?q=infographic

**Comment by alexlittle** [comment]
This should be fixed now.

An outstanding issue though is the design, since the title for each resource in the search results doesn't appear in exactly the same format as when browsing resources. compare: https://covid-19library.org/search/?q=infographic with https://covid-19library.org/tag/view/risk-communication-community-engagement
